export const STARTED = 'INPUTS::STARTED';

export const NAME = 'INPUTS::NAME';

export const SUBJECT = 'INPUTS::SUBJECT';

export const PLATFORM = 'INPUTS::PLATFORM';

export const WHEN = 'INPUTS::WHEN';

export const RESET = 'INPUTS::RESET';

export const SUBJECT_CONFIRM = 'INPUTS::SUBJECT_CONFIRM';

export const SUBJECT_REFUSE = 'INPUTS::SUBJECT_REFUSE';

export const PLATFORM_CONFIRM = 'INPUTS::PLATFORM_CONFIRM';

export const PLATFORM_REFUSE = 'INPUTS::PLATFORM_REFUSE';

export const GET_TRILHAS_STARTED = 'INPUTS::GET_TRILHAS_STARTED';

export const GET_TRILHAS_FINISHED = 'INPUTS::GET_TRILHAS_FINISHED';

export const GET_TRILHAS_FAILED = 'INPUTS::GET_TRILHAS_FAILED';

export const FINISHED = 'INPUTS::FINISHED';

export const UPDATE_GENDER_STARTED = 'INPUTS:UPDATE_GENDER_STARTED';

export const UPDATE_GENDER_FINISHED = 'INPUTS::UPDATE_GENDER_FINISHED';

export const UPDATE_GENDER_FAILED = 'INPUTS::UPDATE_GENDER_FAILED';

export const START_AGAIN = 'INPUTS::START_AGAIN';

export const SET_SUBJECT_URL = 'INPUTS::SET_SUBJECT_URL';